<?php

/*  Copyright 2009-2011 Rafael Gutierrez Martinez
 *  Copyright 2012-2013 Welma WEB MKT LABS, S.L.
 *  Copyright 2014-2016 Where Ideas Simply Come True, S.L.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

namespace providers\apache\httpd\files;

use \devel\builders\text\CNabuTextBuilder;
use \providers\apache\httpd\CApacheHTTPServer;

/**
 * Abstract class to manage all config files of Apache HTTP Server.
 * @author Rafael Gutierrez <rgutierrez@wiscot.com>
 * @version 3.0.0 Surface
 * @package \providers\apache\httpd\files
 */
class CApacheAbstractFile extends CNabuTextBuilder
{
    private $http_server;

    public function __construct(CApacheHTTPServer $http_server)
    {
        parent::__construct();

        $this->http_server = $http_server;
    }

    /**
     * Gets the Apache HTTP Server associate instance.
     * @return CApacheHTTPServer Returns the Apache HTTP Server associated instance.
     */
    public function getHTTPServer()
    {
        return $this->http_server;
    }

    /**
     * Overrides parent method to return the file license as a PHP comment
     * @param string $padding Padding to place at the beginning of each line
     * @return string Returns the license as a PHP comment string
     */
    protected function getLicense($padding = '')
    {
        return "$padding# ===========================================================================\n"
             . "$padding# File generated automatically by Nabu-3\n"
             . "$padding# You can modify this file if you need to add more directives at your risk.\n"
             . "$padding# Remember that this file is autogenerated. If Nabu 3 recreates it,\n"
             . "$padding# additional content added by you will be removed.\n"
             . "$padding# ---------------------------------------------------------------------------\n"
             . "$padding# Created: " . date('Y/m/d H:i:s e') . "\n"
             . "$padding# ===========================================================================\n"
             . nb_apacheLicense($padding . '# ')
             . "$padding# ===========================================================================\n"
             . "\n";
    }

    protected function populateCommonDocs($padding, $commons_path)
    {
        $output = '';

        if (is_dir($commons_path)) {
            $h = opendir($commons_path);
            while (($dir = readdir($h))) {
                $folder = $commons_path . DIRECTORY_SEPARATOR . $dir;
                if ($dir !== '.' && $dir !== '..' && is_dir($folder)) {
                    $output .= "\n"
                            . $padding . "Alias /$dir \"$folder\"\n"
                            . $padding . "<Directory \"$folder\">\n"
                            . $padding . "        AllowOverride All\n"
                            . $padding . "        Require all granted\n"
                            . $padding . "</Directory>\n"
                        ;
                }
            }
            closedir($h);
        }

        return $output;
    }
}
